/*! (c) jTorm and other contributors | www.jtorm.com/license */

const
  {minify} = require('html-minifier'),

  minifyHTMLActionModel = function(html) {
    html = minify(html, {
        caseSensitive: true,
        collapseWhitespace: true,
        collapseInlineTagWhitespace: true,
        conservativeCollapse: true,
        includeAutoGeneratedTags: false,
        keepClosingSlash: true,
        ignoreCustomComments: [
            / ?ko .+ ?/,
            / ?\/ko ?/
        ],
        minifyCSS: true,
        minifyJS: true,
        removeComments: true,
        removeAttributeQuotes: false,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeTagWhitespace: false,
        trimCustomFragments: true
    });

    html = html.replace(/\s\s+/g, ' ');

    return html;
  }

module.exports = {
  minifyHTMLActionModel
};
